Documentation
quarkiverse/quarkus-github-app pull request #178
Opened 2021-07-12 16:12 UTC by yrodiere

First draft, let's talk about it.

2021-07-12 16:23 UTC, gsmet requested changes
I spotted minor issues, looks very good otherwise. Thanks!

2021-07-12 16:23 UTC, gsmet commented on docs/modules/ROOT/pages/testing.adoc
> +as explained in xref:register-github-app.adoc[register the application].
```suggestion
as explained in xref:register-github-app.adoc[Register a GitHub App].
```

2021-07-12 16:23 UTC, gsmet commented on docs/modules/ROOT/pages/testing.adoc
> +configure mocks.
There's something weird here.

2021-07-13 06:12 UTC, yrodiere commented
Thanks. Should be good now; let's wait for CI.

2021-07-13 07:59 UTC, gsmet approved these changes

2021-07-13 07:59 UTC, merged